### ISSUE TITLE
Music runs in slow motion.

### ISSUE THREAD

**Issue by markoni985** [faultythermostat/Tetris-for-the-arduboy#3]
Hi there, I noticed that music is running very slow while the game plays at a normal speed.
Is there any way to increase the speed of the music?
Thank you in advance.

**Comment by faultythermostat** [comment]
The music speed is based off of the speed of the game, so as the game speeds up, so will the music!! It's been a while since I've looked at the program, but ill take a look at adjusting the music speeds or maybe adding an option to play the music at normal speeds!
